# """
# __author__ = "Sky UK Ltd"
# __copyright__ = Copyright © Sky CP Limited 2023.
# All rights reserved. No part of this work may be reproduced,
# stored in a retrieval system of any nature, or transmitted,
# in any form or by any means including photocopying
# and recording, without the prior written permission of Sky,
# the copyright owner.
# __licence__ = "subject to the terms of the licence with Sky UK Ltd'
# __version__ = "1.0"
# """
[tox]
envlist =
    coverage, docs-html, docs-singlehtml, docs-pdf, isort, lint, bumpversion, code-formatter, code-formatter-check, generate-openapi, build-and-publish-confluence
    py36, py37
skip_missing_interpreters = true


[testenv]
description = Run environment
basepython =
    {coverage,docs-html,docs-singlehtml,docs-pdf,isort,lint,bumpversion,code-formatter,code-formatter-check,generate-openapi,build-and-publish-confluence}: {env:TOXPYTHON:python3}
    py36: {env:TOXPYTHON:python3.6}
    py37: {env:TOXPYTHON:python3.7}
setenv =
    PYTHONPATH={toxinidir}/tests
    PYTHONUNBUFFERED=1
    PYTHONDONTWRITEBYTECODE=1
passenv = *
install_command = pip install {opts} {packages}
deps =
    importlib_metadata==4.12.0
    jsonschema==4.18.0
    PyYAML==5.3.1
    pdbpp
    pytest
    pytest-mock
    pytest-fail-slow
    pytest-network
    pytest-xdist
usedevelop = false
commands = py.test -v --disable-network --dist loadfile -n auto --fail-slow 1 {posargs} tests


[testenv:coverage]
description = Run coverage
deps =
    jsonschema==4.18.0
    PyYAML==5.3.1
    pytest
    pytest-mock
    pytest-xdist
    pytest-cov
    pytest-fail-slow
    pytest-network
    coverage
commands =
    py.test -vv --fail-slow 2 --disable-network --dist loadfile -n auto --cov-report= --cov=connectors tests/
    coverage report


[testenv:deploy-coverage]
description = Run coverage in the develop deployment pipeline
deps =
    jsonschema==4.18.0
    PyYAML==5.3.1
    pytest
    pytest-mock
    pytest-xdist
    pytest-cov
    coverage
commands =
    py.test --dist loadfile -n auto --cov-report= --cov=connectors tests/
    coverage report


[testenv:docs-html]
description = Generate HTML docs
skip_install = true
deps = -r{toxinidir}/docs/requirements.txt
commands = sphinx-build -a -E -W -b html {toxinidir}/docs/source/ {toxinidir}/docs/build/html


[testenv:docs-singlehtml]
description = Generate single HTML page docs
skip_install = true
deps = -r{toxinidir}/docs/requirements.txt
commands = sphinx-build -a -E -W -b singlehtml {toxinidir}/docs/source/ {toxinidir}/docs/build/singlehtml


[testenv:docs-pdf]
description = Generate PDF docs
skip_install = true
deps = -r{toxinidir}/docs/requirements.txt
commands = sphinx-build -M latexpdf {toxinidir}/docs/source/ {toxinidir}/docs/build/


[testenv:isort]
description = Sort imports according to PEP rules
skip_install = true
deps = isort==5.5.3
commands = isort src tests setup.py


[testenv:lint]
description = Static syntax checker
skip_install = true
deps =
    isort==5.5.3
    importlib_metadata==4.12.0
    flake8==3.8.3
    flake8-debugger==3.2.1
    pep8-naming==0.11.1
commands =
    isort --check-only --diff --recursive src tests setup.py
    flake8 src tests setup.py

[testenv:bumpversion]
description = Bump version number
skip_install = true
deps =
    bumpversion
commands =
    bumpversion --verbose {posargs}

[testenv:code-formatter]
description = Makes all your code compliant with the code formatter
deps = black==20.8b0
skip_install = true
commands = black --line-length 120 src/ tests/


[testenv:code-formatter-check]
description = Checks if your code if compliant with the code formatter
deps = black==20.8b0
skip_install = true
commands = black --check --line-length 120 src/ tests/ --exclude pybind


[testenv:generate-openapi]
description = Generate openapi v3 specification file
deps =
    prance==0.21.2
    click
    openapi_spec_validator==0.2.9
    jsonschema==4.18.0
    PyYAML==5.3.1
skip_install = true
commands = prance compile {toxinidir}/openapi/index.yaml {toxinidir}/openapi/openapi.yaml


[testenv:validate-openapi]
description = Validate openapi v3 specification file
deps =
    prance==0.21.2
    click
    openapi_spec_validator==0.2.9
    jsonschema==4.18.0
    pip==25.3
    setuptools==80.9.0
    PyYAML==5.3.1
skip_install = true
commands = prance validate {toxinidir}/openapi/index.yaml

[testenv:build-and-publish-confluence]
description = "Build and publish documentation to confluence"
skip_install = true
deps = -r{toxinidir}/docs/requirements.txt
commands = sphinx-build -a -E -v -W -b confluence {toxinidir}/docs/source/ {toxinidir}/docs/build/confluence
