"""
__author__ = "Sky UK Ltd"
__copyright__ = Copyright © Sky CP Limited 2023.
All rights reserved. No part of this work may be reproduced,
stored in a retrieval system of any nature, or transmitted,
in any form or by any means including photocopying
and recording, without the prior written permission of Sky,
the copyright owner.
__licence__ = "subject to the terms of the licence with Sky UK Ltd'
__version__ = "1.0"
"""
# Standard Library
import datetime
from collections import namedtuple

source_list = []
source_list_1 = []
source_list_2 = []
target_list = []
image_list = []
package_list = []
diversion_list = []
service_list = []
custom_config_list = []
custom_config_list_1 = []

image_db_data = [
    {
        "OsVersionDeviceRegionId": 2,
        "device_region_id": 8,
        "file_type": "iso",
        "url": "/bluebird/ios-xr/7.3.0/NCS540/install-image.iso",
        "md5": "ec55d3e698d289f2afd663725127bace",
        "file_size": 2742723234,
        "comments": "7.3.0-V1 is in deprecated status",
        "os": "IOSXR",
        "os_label": "7.3.0-V1",
        "os_version": "7.3.0",
        "validity_state": "Deprecated",
        "vendor": "CISCO",
        "model": "NCS5K",
        "region": "DE",
        "image_id": 2,
    },
]
for image_data in image_db_data:
    d_named = namedtuple("image", image_data.keys())(*image_data.values())
    image_list.append(d_named)

package_db_data = [
    {"image_id": 2, "package_type_value": "XR", "package_name": "ncs540-li-1.0.0.0-r732"},
    {"image_id": 2, "package_type_value": "XR", "package_name": "ncs540-eigrp-1.0.0.0-r732"},
    {"image_id": 2, "package_type_value": "XR", "package_name": "ncs540-isis-1.0.0.0-r732"},
    {
        "image_id": 2,
        "package_type_value": "SYSADMIN-FIX",
        "package_name": "ncs540-sysadmin-shared-7.3.0.1-r732.CSCvx53252",
    },
    {
        "image_id": 2,
        "package_type_value": "SYSADMIN-FIX",
        "package_name": "ncs540-sysadmin-system-7.3.0.2-r732.CSCvy03814",
    },
    {
        "image_id": 2,
        "package_type_value": "SYSADMIN-FIX",
        "package_name": "ncs540-sysadmin-ncs540-7.3.0.5-r732.CSCvz54957",
    },
    {
        "image_id": 2,
        "package_type_value": "SYSADMIN-MOD",
        "package_name": "ncs540-sysadmin-shared-7.3.0.1-r732.CSCvx53252",
    },
    {
        "image_id": 2,
        "package_type_value": "SYSADMIN-MOD",
        "package_name": "ncs540-sysadmin-system-7.3.0.2-r732.CSCvy03814",
    },
    {
        "image_id": 2,
        "package_type_value": "SYSADMIN-MOD",
        "package_name": "ncs540-sysadmin-ncs540-7.3.0.5-r732.CSCvz54957",
    },
]
for package_data in package_db_data:
    d_named = namedtuple("package", package_data.keys())(*package_data.values())
    package_list.append(d_named)

source_db_data = [
    {
        "sequence_id": 2,
        "phase_upgrade_id": 2,
        "steps": 1,
        "sequence_no": 1,
        "next_sequence_id": None,
        "comments": "Upgrade is due to certain reason... ",
        "modifiedOn": datetime.datetime(2023, 7, 11, 13, 10, 19),
        "createdOn": datetime.datetime(2023, 7, 11, 13, 10, 19),
        "createdBy": "Admin",
        "modifiedBy": "Admin",
        "osVersionUpgradeId": 2,
        "source_id": 2,
        "target_id": 5,
        "custom_config_id": 2,
        "source_pre_target": "command in text format",
        "source_post_target": "command in text format",
        "is_rollback_required": True,
        "before_rollback": "target before rollback",
        "after_rollback": "target after rollback",
        "config_mode": "XR",
        "next_config_id": None,
        "role_list_id": 2,
        "role_id1": 11,
        "role_id2": None,
        "role_id3": None,
        "role_id4": None,
        "role_id5": None,
        "role_id6": None,
        "role_id7": None,
        "role_id8": None,
        "role_id9": None,
        "role_id10": None,
        "role_id11": None,
        "role_id12": None,
        "role_id13": None,
        "role_id14": None,
        "role_id15": None,
        "role_id16": None,
        "role_id17": None,
        "role_id18": None,
        "role_id19": None,
        "role_id20": None,
        "role_id21": None,
        "role_id22": None,
        "role_id23": None,
        "role_id24": None,
        "role_id25": None,
        "role_id26": None,
        "role_id27": None,
        "role_id28": None,
        "role_id29": None,
        "role_id30": None,
        "role_id31": None,
        "role_id32": None,
        "role_id33": None,
        "role_id34": None,
        "role_id35": None,
        "role_id36": None,
        "role_id37": None,
        "role_id38": None,
        "sourceOsVersionDeviceRegionId": 2,
        "device_region_id": 8,
        "os_version_id": 2,
        "os_validity_id": 5,
        "parent_device_region_id": 8,
        "parent_os_version_id": 2,
        "os": "IOSXR",
        "source_label": "7.1.0-V1",
        "source_version": "7.1.0",
        "source_state": "Deprecated",
        "vendor": "CISCO",
        "model": "NCS5K",
        "region": "UK",
    },
    {
        "sequence_id": 5,
        "phase_upgrade_id": 5,
        "steps": 2,
        "sequence_no": 1,
        "next_sequence_id": 8,
        "comments": "Upgrade is due to certain reason... ",
        "modifiedOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "createdOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "createdBy": "Admin",
        "modifiedBy": "Admin",
        "osVersionUpgradeId": 5,
        "source_id": 2,
        "target_id": 8,
        "custom_config_id": 2,
        "source_pre_target": "command in text format",
        "source_post_target": "command in text format",
        "is_rollback_required": True,
        "before_rollback": "target before rollback",
        "after_rollback": "target after rollback",
        "config_mode": "XR",
        "next_config_id": 5,
        "role_list_id": 2,
        "role_id1": 11,
        "role_id2": 8,
        "role_id3": None,
        "role_id4": None,
        "role_id5": None,
        "role_id6": None,
        "role_id7": None,
        "role_id8": None,
        "role_id9": None,
        "role_id10": None,
        "role_id11": None,
        "role_id12": None,
        "role_id13": None,
        "role_id14": None,
        "role_id15": None,
        "role_id16": None,
        "role_id17": None,
        "role_id18": None,
        "role_id19": None,
        "role_id20": None,
        "role_id21": None,
        "role_id22": None,
        "role_id23": None,
        "role_id24": None,
        "role_id25": None,
        "role_id26": None,
        "role_id27": None,
        "role_id28": None,
        "role_id29": None,
        "role_id30": None,
        "role_id31": None,
        "role_id32": None,
        "role_id33": None,
        "role_id34": None,
        "role_id35": None,
        "role_id36": None,
        "role_id37": None,
        "role_id38": None,
        "sourceOsVersionDeviceRegionId": 2,
        "device_region_id": 8,
        "os_version_id": 2,
        "os_validity_id": 5,
        "parent_device_region_id": 8,
        "parent_os_version_id": 2,
        "os": "IOSXR",
        "source_label": "7.1.0-V1",
        "source_version": "7.1.0",
        "source_state": "Deprecated",
        "vendor": "CISCO",
        "model": "NCS5K",
        "region": "UK",
    },
    {
        "sequence_id": 8,
        "phase_upgrade_id": 8,
        "steps": 2,
        "sequence_no": 2,
        "next_sequence_id": None,
        "comments": "Upgrade is due to certain reason... ",
        "modifiedOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "createdOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "createdBy": "Admin",
        "modifiedBy": "Admin",
        "osVersionUpgradeId": 8,
        "source_id": 8,
        "target_id": 5,
        "custom_config_id": 2,
        "source_pre_target": "command in text format",
        "source_post_target": "command in text format",
        "is_rollback_required": True,
        "before_rollback": "target before rollback",
        "after_rollback": "target after rollback",
        "config_mode": "XR",
        "next_config_id": 5,
        "role_list_id": 2,
        "role_id1": 11,
        "role_id2": 8,
        "role_id3": None,
        "role_id4": None,
        "role_id5": None,
        "role_id6": None,
        "role_id7": None,
        "role_id8": None,
        "role_id9": None,
        "role_id10": None,
        "role_id11": None,
        "role_id12": None,
        "role_id13": None,
        "role_id14": None,
        "role_id15": None,
        "role_id16": None,
        "role_id17": None,
        "role_id18": None,
        "role_id19": None,
        "role_id20": None,
        "role_id21": None,
        "role_id22": None,
        "role_id23": None,
        "role_id24": None,
        "role_id25": None,
        "role_id26": None,
        "role_id27": None,
        "role_id28": None,
        "role_id29": None,
        "role_id30": None,
        "role_id31": None,
        "role_id32": None,
        "role_id33": None,
        "role_id34": None,
        "role_id35": None,
        "role_id36": None,
        "role_id37": None,
        "role_id38": None,
        "sourceOsVersionDeviceRegionId": 8,
        "device_region_id": 8,
        "os_version_id": 8,
        "os_validity_id": 8,
        "parent_device_region_id": 8,
        "parent_os_version_id": 8,
        "os": "IOSXR",
        "source_label": "7.3.0-V1",
        "source_version": "7.3.0",
        "source_state": "Current",
        "vendor": "CISCO",
        "model": "NCS5K",
        "region": "UK",
    },
]
for source_data in source_db_data:
    d_named = namedtuple("source", source_data.keys())(*source_data.values())
    source_list.append(d_named)

source_db_data_1 = [
    {
        "sequence_id": 5,
        "phase_upgrade_id": 5,
        "steps": 2,
        "sequence_no": 1,
        "next_sequence_id": 8,
        "comments": "Upgrade is due to certain reason... ",
        "modifiedOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "createdOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "createdBy": "Admin",
        "modifiedBy": "Admin",
        "osVersionUpgradeId": 5,
        "source_id": 2,
        "target_id": 8,
        "source_pre_target": "command in text format",
        "source_post_target": "command in text format",
        "sourceOsVersionDeviceRegionId": 2,
        "device_region_id": 8,
        "os_version_id": 2,
        "os_validity_id": 5,
        "parent_device_region_id": 8,
        "parent_os_version_id": 2,
        "os": "IOSXR",
        "source_label": "7.1.0-V1",
        "source_version": "7.1.0",
        "source_state": "Deprecated",
        "vendor": "CISCO",
        "model": "NCS5K",
        "region": "UK",
    },
]
for source_data in source_db_data_1:
    d_named = namedtuple("source", source_data.keys())(*source_data.values())
    source_list_1.append(d_named)

source_db_data_2 = [
    {
        "sequence_id": 8,
        "phase_upgrade_id": 8,
        "steps": 2,
        "sequence_no": 2,
        "next_sequence_id": None,
        "comments": "Upgrade is due to certain reason... ",
        "modifiedOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "createdOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "createdBy": "Admin",
        "modifiedBy": "Admin",
        "osVersionUpgradeId": 8,
        "source_id": 8,
        "target_id": 5,
        "source_pre_target": "command in text format",
        "source_post_target": "command in text format",
        "sourceOsVersionDeviceRegionId": 8,
        "device_region_id": 8,
        "os_version_id": 8,
        "os_validity_id": 8,
        "parent_device_region_id": 8,
        "parent_os_version_id": 8,
        "os": "IOSXR",
        "source_label": "7.3.0-V1",
        "source_version": "7.3.0",
        "source_state": "Current",
        "vendor": "CISCO",
        "model": "NCS5K",
        "region": "UK",
    },
]
for source_data in source_db_data_2:
    d_named = namedtuple("source", source_data.keys())(*source_data.values())
    source_list_2.append(d_named)

target_db_data = [
    {
        "sequence_id": 2,
        "phase_upgrade_id": 2,
        "steps": 1,
        "sequence_no": 1,
        "next_sequence_id": None,
        "comments": "Upgrade is due to certain reason... ",
        "modifiedOn": datetime.datetime(2023, 7, 11, 13, 10, 19),
        "createdOn": datetime.datetime(2023, 7, 11, 13, 10, 19),
        "createdBy": "Admin",
        "modifiedBy": "Admin",
        "osVersionUpgradeId": 2,
        "source_id": 2,
        "target_id": 5,
        "custom_config_id": 2,
        "target_pre_target": "command in text format",
        "target_post_target": "command in text format",
        "is_rollback_required": True,
        "before_rollback": "command in text format",
        "after_rollback": "command in text format",
        "config_mode": "XR",
        "next_config_id": None,
        "role_list_id": 2,
        "role_id1": 11,
        "role_id2": None,
        "role_id3": None,
        "role_id4": None,
        "role_id5": None,
        "role_id6": None,
        "role_id7": None,
        "role_id8": None,
        "role_id9": None,
        "role_id10": None,
        "role_id11": None,
        "role_id12": None,
        "role_id13": None,
        "role_id14": None,
        "role_id15": None,
        "role_id16": None,
        "role_id17": None,
        "role_id18": None,
        "role_id19": None,
        "role_id20": None,
        "role_id21": None,
        "role_id22": None,
        "role_id23": None,
        "role_id24": None,
        "role_id25": None,
        "role_id26": None,
        "role_id27": None,
        "role_id28": None,
        "role_id29": None,
        "role_id30": None,
        "role_id31": None,
        "role_id32": None,
        "role_id33": None,
        "role_id34": None,
        "role_id35": None,
        "role_id36": None,
        "role_id37": None,
        "role_id38": None,
        "targetOsVersionDeviceRegionId": 5,
        "device_region_id": 8,
        "os_version_id": 5,
        "os_validity_id": 8,
        "parent_device_region_id": 8,
        "parent_os_version_id": 5,
        "os": "IOSXR",
        "target_label": "7.5.1-V1",
        "target_version": "7.5.1",
        "target_state": "Current",
        "vendor": "CISCO",
        "model": "NCS5K",
        "region": "UK",
    },
    {
        "sequence_id": 5,
        "phase_upgrade_id": 5,
        "steps": 2,
        "sequence_no": 1,
        "next_sequence_id": 8,
        "comments": "Upgrade is due to certain reason... ",
        "modifiedOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "createdOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "createdBy": "Admin",
        "modifiedBy": "Admin",
        "osVersionUpgradeId": 5,
        "source_id": 2,
        "target_id": 8,
        "custom_config_id": 2,
        "target_pre_target": "command in text format",
        "target_post_target": "command in text format",
        "is_rollback_required": True,
        "before_rollback": "command in text format",
        "after_rollback": "command in text format",
        "config_mode": "XR",
        "next_config_id": None,
        "role_list_id": 2,
        "role_id1": 11,
        "role_id2": None,
        "role_id3": None,
        "role_id4": None,
        "role_id5": None,
        "role_id6": None,
        "role_id7": None,
        "role_id8": None,
        "role_id9": None,
        "role_id10": None,
        "role_id11": None,
        "role_id12": None,
        "role_id13": None,
        "role_id14": None,
        "role_id15": None,
        "role_id16": None,
        "role_id17": None,
        "role_id18": None,
        "role_id19": None,
        "role_id20": None,
        "role_id21": None,
        "role_id22": None,
        "role_id23": None,
        "role_id24": None,
        "role_id25": None,
        "role_id26": None,
        "role_id27": None,
        "role_id28": None,
        "role_id29": None,
        "role_id30": None,
        "role_id31": None,
        "role_id32": None,
        "role_id33": None,
        "role_id34": None,
        "role_id35": None,
        "role_id36": None,
        "role_id37": None,
        "role_id38": None,
        "targetOsVersionDeviceRegionId": 8,
        "device_region_id": 8,
        "os_version_id": 8,
        "os_validity_id": 8,
        "parent_device_region_id": 8,
        "parent_os_version_id": 8,
        "os": "IOSXR",
        "target_label": "7.3.0-V1",
        "target_version": "7.3.0",
        "target_state": "Current",
        "vendor": "CISCO",
        "model": "NCS5K",
        "region": "UK",
    },
    {
        "sequence_id": 8,
        "phase_upgrade_id": 8,
        "steps": 2,
        "sequence_no": 2,
        "next_sequence_id": None,
        "comments": "Upgrade is due to certain reason... ",
        "modifiedOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "createdOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "createdBy": "Admin",
        "modifiedBy": "Admin",
        "osVersionUpgradeId": 8,
        "source_id": 8,
        "target_id": 5,
        "custom_config_id": 2,
        "target_pre_target": "command in text format",
        "target_post_target": "command in text format",
        "is_rollback_required": True,
        "before_rollback": "command in text format",
        "after_rollback": "command in text format",
        "config_mode": "XR",
        "next_config_id": None,
        "role_list_id": 2,
        "role_id1": 11,
        "role_id2": None,
        "role_id3": None,
        "role_id4": None,
        "role_id5": None,
        "role_id6": None,
        "role_id7": None,
        "role_id8": None,
        "role_id9": None,
        "role_id10": None,
        "role_id11": None,
        "role_id12": None,
        "role_id13": None,
        "role_id14": None,
        "role_id15": None,
        "role_id16": None,
        "role_id17": None,
        "role_id18": None,
        "role_id19": None,
        "role_id20": None,
        "role_id21": None,
        "role_id22": None,
        "role_id23": None,
        "role_id24": None,
        "role_id25": None,
        "role_id26": None,
        "role_id27": None,
        "role_id28": None,
        "role_id29": None,
        "role_id30": None,
        "role_id31": None,
        "role_id32": None,
        "role_id33": None,
        "role_id34": None,
        "role_id35": None,
        "role_id36": None,
        "role_id37": None,
        "role_id38": None,
        "targetOsVersionDeviceRegionId": 5,
        "device_region_id": 8,
        "os_version_id": 5,
        "os_validity_id": 8,
        "parent_device_region_id": 8,
        "parent_os_version_id": 5,
        "os": "IOSXR",
        "target_label": "7.5.1-V1",
        "target_version": "7.5.1",
        "target_state": "Current",
        "vendor": "CISCO",
        "model": "NCS5K",
        "region": "UK",
    },
]
for target_data in target_db_data:
    d_named = namedtuple("target", target_data.keys())(*target_data.values())
    target_list.append(d_named)

custom_config_db_data = [
    {
        "custom_config_id": 2,
        "pre_target_upgrade_conf": "command in text format",
        "post_target_upgrade_conf": "command in text format",
        "is_rollback_required": True,
        "before_rollback": "target before rollback",
        "after_rollback": "target after rollback",
        "config_mode": "XR",
        "next_config_id": None,
        "role_list_id": 2,
        "role_id1": 11,
        "role_id2": None,
        "role_id3": None,
        "role_id4": None,
        "role_id5": None,
        "role_id6": None,
        "role_id7": None,
        "role_id8": None,
        "role_id9": None,
        "role_id10": None,
        "role_id11": None,
        "role_id12": None,
        "role_id13": None,
        "role_id14": None,
        "role_id15": None,
        "role_id16": None,
        "role_id17": None,
        "role_id18": None,
        "role_id19": None,
        "role_id20": None,
        "role_id21": None,
        "role_id22": None,
        "role_id23": None,
        "role_id24": None,
        "role_id25": None,
        "role_id26": None,
        "role_id27": None,
        "role_id28": None,
        "role_id29": None,
        "role_id30": None,
        "role_id31": None,
        "role_id32": None,
        "role_id33": None,
        "role_id34": None,
        "role_id35": None,
        "role_id36": None,
        "role_id37": None,
        "role_id38": None,
    },
]

for custom_config_data in custom_config_db_data:
    d_named = namedtuple("custom_config", custom_config_data.keys())(*custom_config_data.values())
    custom_config_list.append(d_named)


custom_config_db_data_1 = [
    {
        "custom_config_id": 3,
        "id": 3,
        "pre_target_upgrade_conf": "command in text format",
        "post_target_upgrade_conf": "command in text format",
        "is_rollback_required": True,
        "before_rollback": "target before rollback",
        "after_rollback": "target after rollback",
        "config_mode": "XR",
        "next_config_id": 4,
        "role_list_id": 3,
        "role_id1": 11,
        "role_id2": None,
        "role_id3": None,
        "role_id4": None,
        "role_id5": None,
        "role_id6": None,
        "role_id7": None,
        "role_id8": None,
        "role_id9": None,
        "role_id10": None,
        "role_id11": None,
        "role_id12": None,
        "role_id13": None,
        "role_id14": None,
        "role_id15": None,
        "role_id16": None,
        "role_id17": None,
        "role_id18": None,
        "role_id19": None,
        "role_id20": None,
        "role_id21": None,
        "role_id22": None,
        "role_id23": None,
        "role_id24": None,
        "role_id25": None,
        "role_id26": None,
        "role_id27": None,
        "role_id28": None,
        "role_id29": None,
        "role_id30": None,
        "role_id31": None,
        "role_id32": None,
        "role_id33": None,
        "role_id34": None,
        "role_id35": None,
        "role_id36": None,
        "role_id37": None,
        "role_id38": None,
    },
    {
        "custom_config_id": 4,
        "id": 4,
        "pre_target_upgrade_conf": "command in text format",
        "post_target_upgrade_conf": "command in text format",
        "is_rollback_required": True,
        "before_rollback": "target before rollback",
        "after_rollback": "target after rollback",
        "config_mode": "XR",
        "next_config_id": None,
        "role_list_id": 4,
        "role_id1": 11,
        "role_id2": None,
        "role_id3": None,
        "role_id4": None,
        "role_id5": None,
        "role_id6": None,
        "role_id7": None,
        "role_id8": None,
        "role_id9": None,
        "role_id10": None,
        "role_id11": None,
        "role_id12": None,
        "role_id13": None,
        "role_id14": None,
        "role_id15": None,
        "role_id16": None,
        "role_id17": None,
        "role_id18": None,
        "role_id19": None,
        "role_id20": None,
        "role_id21": None,
        "role_id22": None,
        "role_id23": None,
        "role_id24": None,
        "role_id25": None,
        "role_id26": None,
        "role_id27": None,
        "role_id28": None,
        "role_id29": None,
        "role_id30": None,
        "role_id31": None,
        "role_id32": None,
        "role_id33": None,
        "role_id34": None,
        "role_id35": None,
        "role_id36": None,
        "role_id37": None,
        "role_id38": None,
    },
]

for custom_config_data in custom_config_db_data_1:
    d_named = namedtuple("custom_config", custom_config_data.keys())(*custom_config_data.values())
    custom_config_list_1.append([d_named])

traffic_db_data = [
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "UK",
        "role": "SUPER CORE",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "UK",
        "role": "SUPER CORE",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "RSVP",
        "region": "UK",
        "role": "SUPER CORE",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 60,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "UK",
        "role": "TRANSPORT AGG",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "CDN",
        "region": "UK",
        "role": "TRANSPORT AGG",
        "sequence": 2,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "L2-BNG",
        "region": "UK",
        "role": "TRANSPORT AGG",
        "sequence": 3,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 600,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "L2-BNG",
        "region": "UK",
        "role": "TRANSPORT AGG",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "UK",
        "role": "TRANSPORT AGG",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "RSVP",
        "region": "UK",
        "role": "TRANSPORT AGG",
        "sequence": 3,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 60,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "L2-BNG",
        "region": "UK",
        "role": "TRANSPORT AGG",
        "sequence": 4,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 600,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "CDN",
        "region": "UK",
        "role": "TRANSPORT AGG",
        "sequence": 5,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "UK",
        "role": "P&T",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "EBGP",
        "region": "UK",
        "role": "P&T",
        "sequence": 2,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "UK",
        "role": "P&T",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "EBGP",
        "region": "UK",
        "role": "P&T",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "UK",
        "role": "GROUP ASBR",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "OSPF",
        "region": "UK",
        "role": "GROUP ASBR",
        "sequence": 2,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Core",
        "model": "NCS5K",
        "protocol": "SB-Physical",
        "region": "UK",
        "role": "GROUP ASBR",
        "sequence": 3,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "UK",
        "role": "GROUP ASBR",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "OSPF",
        "region": "UK",
        "role": "GROUP ASBR",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Core",
        "model": "NCS5K",
        "protocol": "SB-Physical",
        "region": "UK",
        "role": "GROUP ASBR",
        "sequence": 3,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "SUPER CORE",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "SUPER CORE",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "METRO AGG",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Gi0/0/0/23",
        "model": "NCS5K",
        "protocol": "EVPN",
        "region": "IT",
        "role": "METRO AGG",
        "sequence": 2,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "CFP2-Port",
        "region": "IT",
        "role": "METRO AGG",
        "sequence": 3,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "L2-BNG",
        "region": "IT",
        "role": "METRO AGG",
        "sequence": 4,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 600,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "L2-BNG",
        "region": "IT",
        "role": "METRO AGG",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "METRO AGG",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Gi0/0/0/23",
        "model": "NCS5K",
        "protocol": "EVPN",
        "region": "IT",
        "role": "METRO AGG",
        "sequence": 3,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 600,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "L2-BNG",
        "region": "IT",
        "role": "METRO AGG",
        "sequence": 4,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "CFP2-Port",
        "region": "IT",
        "role": "METRO AGG",
        "sequence": 5,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "TRANSPORT AGG",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Gi0/0/0/23",
        "model": "NCS5K",
        "protocol": "EVPN",
        "region": "IT",
        "role": "TRANSPORT AGG",
        "sequence": 2,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "L2-BNG",
        "region": "IT",
        "role": "TRANSPORT AGG",
        "sequence": 3,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 600,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "CFP2-Port",
        "region": "IT",
        "role": "TRANSPORT AGG",
        "sequence": 4,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "L2-BNG",
        "region": "IT",
        "role": "TRANSPORT AGG",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "TRANSPORT AGG",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Gi0/0/0/23",
        "model": "NCS5K",
        "protocol": "EVPN",
        "region": "IT",
        "role": "TRANSPORT AGG",
        "sequence": 3,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 600,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "L2-BNG",
        "region": "IT",
        "role": "TRANSPORT AGG",
        "sequence": 4,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "CFP2-Port",
        "region": "IT",
        "role": "TRANSPORT AGG",
        "sequence": 5,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "P&T",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "EBGP",
        "region": "IT",
        "role": "P&T",
        "sequence": 2,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "BGP",
        "region": "IT",
        "role": "P&T",
        "sequence": 3,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 300,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "P&T",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "BGP",
        "region": "IT",
        "role": "P&T",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 310,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "EBGP",
        "region": "IT",
        "role": "P&T",
        "sequence": 3,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "GROUP ASBR",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Core",
        "model": "NCS5K",
        "protocol": "SB-Physical",
        "region": "IT",
        "role": "GROUP ASBR",
        "sequence": 2,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "GROUP ASBR",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Core",
        "model": "NCS5K",
        "protocol": "SB-Physical",
        "region": "IT",
        "role": "GROUP ASBR",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "GROUP SUPER CORE",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "OSPF",
        "region": "IT",
        "role": "GROUP SUPER CORE",
        "sequence": 2,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "GROUP SUPER CORE",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "OSPF",
        "region": "IT",
        "role": "GROUP SUPER CORE",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "COMCAST SDC",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Core",
        "model": "NCS5K",
        "protocol": "SB-Physical",
        "region": "IT",
        "role": "COMCAST SDC",
        "sequence": 2,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "IT",
        "role": "COMCAST SDC",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Core",
        "model": "NCS5K",
        "protocol": "SB-Physical",
        "region": "IT",
        "role": "COMCAST SDC",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "DE",
        "role": "GROUP SUPER CORE",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "OSPF",
        "region": "DE",
        "role": "GROUP SUPER CORE",
        "sequence": 2,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "DE",
        "role": "GROUP SUPER CORE",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "OSPF",
        "region": "DE",
        "role": "GROUP SUPER CORE",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "DE",
        "role": "COMCAST SDC",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Core",
        "model": "NCS5K",
        "protocol": "SB-Physical",
        "region": "DE",
        "role": "COMCAST SDC",
        "sequence": 2,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "DE",
        "role": "COMCAST SDC",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Core",
        "model": "NCS5K",
        "protocol": "SB-Physical",
        "region": "DE",
        "role": "COMCAST SDC",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "DE",
        "role": "GROUP XVP",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "OSPF",
        "region": "DE",
        "role": "GROUP XVP",
        "sequence": 2,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Core",
        "model": "NCS5K",
        "protocol": "SB-Physical",
        "region": "DE",
        "role": "GROUP XVP",
        "sequence": 3,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "DE",
        "role": "GROUP XVP",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "OSPF",
        "region": "DE",
        "role": "GROUP XVP",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": "Core",
        "model": "NCS5K",
        "protocol": "SB-Physical",
        "region": "DE",
        "role": "GROUP XVP",
        "sequence": 3,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "DE",
        "role": "GROUP P&T",
        "sequence": 1,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "EBGP",
        "region": "DE",
        "role": "GROUP P&T",
        "sequence": 2,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "BGP",
        "region": "DE",
        "role": "GROUP P&T",
        "sequence": 3,
        "traffic_type": "On",
        "vendor": "CISCO",
        "wait_time": 300,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "ISIS",
        "region": "DE",
        "role": "GROUP P&T",
        "sequence": 1,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "BGP",
        "region": "DE",
        "role": "GROUP P&T",
        "sequence": 2,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 300,
    },
    {
        "exclusion": None,
        "model": "NCS5K",
        "protocol": "EBGP",
        "region": "DE",
        "role": "GROUP P&T",
        "sequence": 3,
        "traffic_type": "Off",
        "vendor": "CISCO",
        "wait_time": 0,
    },
]
for traffic_data in traffic_db_data:
    d_named = namedtuple("traffic", traffic_data.keys())(*traffic_data.values())
    diversion_list.append(d_named)

service_db_data = [
    {"model": "NCS5K", "role": "super-core", "vendor": "CISCO", "is_service_required": False, "region": "UK"},
    {"model": "NCS5K", "role": "cdn", "vendor": "CISCO", "is_service_required": False, "region": "UK"},
    {"model": "NCS5K", "role": "metro-agg", "vendor": "CISCO", "is_service_required": False, "region": "UK"},
    {"model": "NCS5K", "role": "transport-agg", "vendor": "CISCO", "is_service_required": True, "region": "UK"},
    {"model": "NCS5K", "role": "peer-and-transit", "vendor": "CISCO", "is_service_required": False, "region": "UK"},
    {"model": "NCS5K", "role": "group-asbr", "vendor": "CISCO", "is_service_required": False, "region": "UK"},
    {"model": "NCS5K", "role": "group-super-core", "vendor": "CISCO", "is_service_required": False, "region": "UK"},
    {"model": "NCS5K", "role": "comcast-sdc", "vendor": "CISCO", "is_service_required": False, "region": "UK"},
    {"model": "NCS5K", "role": "group-xvp", "vendor": "CISCO", "is_service_required": False, "region": "UK"},
    {
        "model": "NCS5K",
        "role": "group-peer-and-transit",
        "vendor": "CISCO",
        "is_service_required": False,
        "region": "UK",
    },
    {"model": "NCS5K", "role": "super-core", "vendor": "CISCO", "is_service_required": False, "region": "IT"},
    {"model": "NCS5K", "role": "cdn", "vendor": "CISCO", "is_service_required": False, "region": "IT"},
    {"model": "NCS5K", "role": "metro-agg", "vendor": "CISCO", "is_service_required": True, "region": "IT"},
    {"model": "NCS5K", "role": "transport-agg", "vendor": "CISCO", "is_service_required": True, "region": "IT"},
    {"model": "NCS5K", "role": "peer-and-transit", "vendor": "CISCO", "is_service_required": False, "region": "IT"},
    {"model": "NCS5K", "role": "group-asbr", "vendor": "CISCO", "is_service_required": False, "region": "IT"},
    {"model": "NCS5K", "role": "group-super-core", "vendor": "CISCO", "is_service_required": False, "region": "IT"},
    {"model": "NCS5K", "role": "comcast-sdc", "vendor": "CISCO", "is_service_required": False, "region": "IT"},
    {"model": "NCS5K", "role": "group-xvp", "vendor": "CISCO", "is_service_required": False, "region": "IT"},
    {
        "model": "NCS5K",
        "role": "group-peer-and-transit",
        "vendor": "CISCO",
        "is_service_required": False,
        "region": "IT",
    },
    {"model": "NCS5K", "role": "super-core", "vendor": "CISCO", "is_service_required": False, "region": "DE"},
    {"model": "NCS5K", "role": "cdn", "vendor": "CISCO", "is_service_required": False, "region": "DE"},
    {"model": "NCS5K", "role": "metro-agg", "vendor": "CISCO", "is_service_required": False, "region": "DE"},
    {"model": "NCS5K", "role": "transport-agg", "vendor": "CISCO", "is_service_required": False, "region": "DE"},
    {"model": "NCS5K", "role": "peer-and-transit", "vendor": "CISCO", "is_service_required": False, "region": "DE"},
    {"model": "NCS5K", "role": "group-asbr", "vendor": "CISCO", "is_service_required": False, "region": "DE"},
    {"model": "NCS5K", "role": "group-super-core", "vendor": "CISCO", "is_service_required": False, "region": "DE"},
    {"model": "NCS5K", "role": "comcast-sdc", "vendor": "CISCO", "is_service_required": False, "region": "DE"},
    {"model": "NCS5K", "role": "group-xvp", "vendor": "CISCO", "is_service_required": False, "region": "DE"},
    {
        "model": "NCS5K",
        "role": "group-peer-and-transit",
        "vendor": "CISCO",
        "is_service_required": False,
        "region": "DE",
    },
    {"model": "NCS5K", "role": "super-core", "vendor": "CISCO", "is_service_required": False, "region": "IE"},
    {"model": "NCS5K", "role": "cdn", "vendor": "CISCO", "is_service_required": False, "region": "IE"},
    {"model": "NCS5K", "role": "metro-agg", "vendor": "CISCO", "is_service_required": False, "region": "IE"},
    {"model": "NCS5K", "role": "transport-agg", "vendor": "CISCO", "is_service_required": False, "region": "IE"},
    {"model": "NCS5K", "role": "peer-and-transit", "vendor": "CISCO", "is_service_required": False, "region": "IE"},
    {"model": "NCS5K", "role": "group-asbr", "vendor": "CISCO", "is_service_required": False, "region": "IE"},
    {"model": "NCS5K", "role": "group-super-core", "vendor": "CISCO", "is_service_required": False, "region": "IE"},
    {"model": "NCS5K", "role": "comcast-sdc", "vendor": "CISCO", "is_service_required": False, "region": "IE"},
    {"model": "NCS5K", "role": "group-xvp", "vendor": "CISCO", "is_service_required": False, "region": "IE"},
    {
        "model": "NCS5K",
        "role": "group-peer-and-transit",
        "vendor": "CISCO",
        "is_service_required": False,
        "region": "IE",
    },
]
for service_data in service_db_data:
    d_named = namedtuple("traffic", service_data.keys())(*service_data.values())
    service_list.append(d_named)

final_response = {
    "limit": 3,
    "offset": 0,
    "status": "SUCCESS",
    "resultSet": [
        {
            "currentLabel": "7.1.0-V1",
            "currentState": "Deprecated",
            "currentVersion": "7.1.0",
            "deviceModel": "NCS5K",
            "deviceVendor": "CISCO",
            "osVersionUpgradeId": 2,
            "region": "UK",
            "targetLabel": "7.5.1-V1",
            "targetState": "Current",
            "targetVersion": "7.5.1",
        },
        {
            "currentLabel": "7.1.0-V1",
            "currentState": "Deprecated",
            "currentVersion": "7.1.0",
            "deviceModel": "NCS5K",
            "deviceVendor": "CISCO",
            "osVersionUpgradeId": 5,
            "region": "UK",
            "targetLabel": "7.3.0-V1",
            "targetState": "Current",
            "targetVersion": "7.3.0",
        },
        {
            "currentLabel": "7.3.0-V1",
            "currentState": "Current",
            "currentVersion": "7.3.0",
            "deviceModel": "NCS5K",
            "deviceVendor": "CISCO",
            "osVersionUpgradeId": 8,
            "region": "UK",
            "targetLabel": "7.5.1-V1",
            "targetState": "Current",
            "targetVersion": "7.5.1",
        },
    ],
    "total": 3,
}

final_response2 = [
    {
        "osVersionDeviceRegionId": 2,
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "region": "UK",
        "currentOsVersion": "7.1.0",
        "currentOsLabel": "7.1.0-V1",
        "createdBy": "Admin",
        "createdOn": datetime.datetime(2023, 7, 11, 13, 10, 19),
        "modifiedBy": "Admin",
        "modifiedOn": datetime.datetime(2023, 7, 11, 13, 10, 19),
        "status": "SUCCESS",
        "upgradeDetails": {
            "upgradeSteps": 1,
            "targetOs": {
                "osVersionDeviceRegionId": 5,
                "osVersion": "7.5.1",
                "osLabel": "7.5.1-V1",
                "sequence": 1,
                "customConfig": [
                    {
                        "beforeUpgrade": "command in text format",
                        "afterUpgrade": "command in text format",
                        "isRollbackRequired": True,
                        "beforeRollback": "target before rollback",
                        "afterRollback": "target after rollback",
                        "configMode": "XR",
                        "deviceRole": ["transport-agg"],
                    }
                ],
            },
            "comments": "Upgrade is due to certain reason... ",
        },
    },
    {
        "osVersionDeviceRegionId": 2,
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "region": "UK",
        "currentOsVersion": "7.1.0",
        "currentOsLabel": "7.1.0-V1",
        "createdBy": "Admin",
        "createdOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "modifiedBy": "Admin",
        "modifiedOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "status": "SUCCESS",
        "upgradeDetails": {
            "upgradeSteps": 2,
            "targetOs": {
                "osVersionDeviceRegionId": 5,
                "osVersion": "7.5.1",
                "osLabel": "7.5.1-V1",
                "sequence": 2,
                "customConfig": [
                    {
                        "beforeUpgrade": "command in text format",
                        "afterUpgrade": "command in text format",
                        "isRollbackRequired": True,
                        "beforeRollback": "target before rollback",
                        "afterRollback": "target after rollback",
                        "configMode": "XR",
                        "deviceRole": ["transport-agg"],
                    }
                ],
            },
            "comments": "Upgrade is due to certain reason... ",
            "intermediateSteps": [
                {
                    "osVersionDeviceRegionId": 8,
                    "osVersion": "7.3.0",
                    "osLabel": "7.3.0-V1",
                    "sequence": 1,
                    "customConfig": [
                        {
                            "beforeUpgrade": "command in text format",
                            "afterUpgrade": "command in text format",
                            "isRollbackRequired": True,
                            "beforeRollback": "target before rollback",
                            "afterRollback": "target after rollback",
                            "configMode": "XR",
                            "deviceRole": ["transport-agg"],
                        }
                    ],
                }
            ],
        },
    },
]


final_response3 = [
    {
        "osVersionDeviceRegionId": 2,
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "region": "UK",
        "currentOsVersion": "7.1.0",
        "currentOsLabel": "7.1.0-V1",
        "createdBy": "Admin",
        "createdOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "modifiedBy": "Admin",
        "modifiedOn": datetime.datetime(2023, 7, 11, 13, 11, 50),
        "status": "SUCCESS",
        "upgradeDetails": {
            "upgradeSteps": 2,
            "targetOs": {
                "osVersionDeviceRegionId": 5,
                "osVersion": "7.5.1",
                "osLabel": "7.5.1-V1",
                "sequence": 2,
                "customConfig": [
                    {
                        "beforeUpgrade": "command in text format",
                        "afterUpgrade": "command in text format",
                        "isRollbackRequired": True,
                        "beforeRollback": "target before rollback",
                        "afterRollback": "target after rollback",
                        "configMode": "XR",
                        "deviceRole": ["transport-agg"],
                    }
                ],
            },
            "comments": "Upgrade is due to certain reason... ",
            "intermediateSteps": [
                {
                    "osVersionDeviceRegionId": 8,
                    "osVersion": "7.3.0",
                    "osLabel": "7.3.0-V1",
                    "sequence": 1,
                    "customConfig": [
                        {
                            "beforeUpgrade": "command in text format",
                            "afterUpgrade": "command in text format",
                            "isRollbackRequired": True,
                            "beforeRollback": "target before rollback",
                            "afterRollback": "target after rollback",
                            "configMode": "XR",
                            "deviceRole": ["transport-agg"],
                        }
                    ],
                }
            ],
        },
    }
]

final_response4 = {
    "deviceModel": "NCS5K",
    "deviceVendor": "CISCO",
    "comments": "7.3.0-V1 is in deprecated status",
    "osVersionDeviceRegionId": 2,
    "status": "SUCCESS",
    "osDetails": {
        "imageFiles": [
            {
                "fileName": "/bluebird/ios-xr/7.3.0/NCS540/install-image.iso",
                "imageSize": 2742723234,
                "imageType": "iso",
                "md5Value": "ec55d3e698d289f2afd663725127bace",
            }
        ],
        "packageDetails": (
            {
                "packages": ["ncs540-li-1.0.0.0-r732", "ncs540-eigrp-1.0.0.0-r732", "ncs540-isis-1.0.0.0-r732"],
                "type": "XR",
            },
            {
                "packages": [
                    "ncs540-sysadmin-shared-7.3.0.1-r732.CSCvx53252",
                    "ncs540-sysadmin-system-7.3.0.2-r732.CSCvy03814",
                    "ncs540-sysadmin-ncs540-7.3.0.5-r732.CSCvz54957",
                ],
                "type": "SYSADMIN-FIX",
            },
            {
                "packages": [
                    "ncs540-sysadmin-shared-7.3.0.1-r732.CSCvx53252",
                    "ncs540-sysadmin-system-7.3.0.2-r732.CSCvy03814",
                    "ncs540-sysadmin-ncs540-7.3.0.5-r732.CSCvz54957",
                ],
                "type": "SYSADMIN-MOD",
            },
        ),
    },
    "osLabel": "7.3.0-V1",
    "osStatus": "Deprecated",
    "osVersion": "7.3.0",
    "region": "DE",
}

final_response5 = {
    "limit": 1,
    "offset": 0,
    "total": 3,
    "status": "SUCCESS",
    "resultSet": [
        {
            "osVersionUpgradeId": 2,
            "deviceVendor": "CISCO",
            "deviceModel": "NCS5K",
            "region": "UK",
            "currentVersion": "7.1.0",
            "currentLabel": "7.1.0-V1",
            "currentState": "Deprecated",
            "targetVersion": "7.5.1",
            "targetLabel": "7.5.1-V1",
            "targetState": "Current",
        }
    ],
}

final_response6 = [
    {
        "deviceModel": "NCS5K",
        "deviceRole": "COMCAST SDC",
        "deviceVendor": "CISCO",
        "region": "DE",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": "Core", "sequence": 2, "step": "SB-Physical", "waitTimeSec": 0},
        ],
        "trafficOnStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": "Core", "sequence": 2, "step": "SB-Physical", "waitTimeSec": 0},
        ],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "COMCAST SDC",
        "deviceVendor": "CISCO",
        "region": "IT",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": "Core", "sequence": 2, "step": "SB-Physical", "waitTimeSec": 0},
        ],
        "trafficOnStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": "Core", "sequence": 2, "step": "SB-Physical", "waitTimeSec": 0},
        ],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "GROUP ASBR",
        "deviceVendor": "CISCO",
        "region": "IT",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": "Core", "sequence": 2, "step": "SB-Physical", "waitTimeSec": 0},
        ],
        "trafficOnStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": "Core", "sequence": 2, "step": "SB-Physical", "waitTimeSec": 0},
        ],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "GROUP ASBR",
        "deviceVendor": "CISCO",
        "region": "UK",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "OSPF", "waitTimeSec": 0},
            {"exclusion": "Core", "sequence": 3, "step": "SB-Physical", "waitTimeSec": 0},
        ],
        "trafficOnStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "OSPF", "waitTimeSec": 0},
            {"exclusion": "Core", "sequence": 3, "step": "SB-Physical", "waitTimeSec": 0},
        ],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "GROUP P&T",
        "deviceVendor": "CISCO",
        "region": "DE",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "BGP", "waitTimeSec": 300},
            {"exclusion": None, "sequence": 3, "step": "EBGP", "waitTimeSec": 0},
        ],
        "trafficOnStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "EBGP", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 3, "step": "BGP", "waitTimeSec": 300},
        ],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "GROUP SUPER CORE",
        "deviceVendor": "CISCO",
        "region": "DE",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "OSPF", "waitTimeSec": 0},
        ],
        "trafficOnStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "OSPF", "waitTimeSec": 0},
        ],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "GROUP SUPER CORE",
        "deviceVendor": "CISCO",
        "region": "IT",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "OSPF", "waitTimeSec": 0},
        ],
        "trafficOnStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "OSPF", "waitTimeSec": 0},
        ],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "GROUP XVP",
        "deviceVendor": "CISCO",
        "region": "DE",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "OSPF", "waitTimeSec": 0},
            {"exclusion": "Core", "sequence": 3, "step": "SB-Physical", "waitTimeSec": 0},
        ],
        "trafficOnStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "OSPF", "waitTimeSec": 0},
            {"exclusion": "Core", "sequence": 3, "step": "SB-Physical", "waitTimeSec": 0},
        ],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "METRO AGG",
        "deviceVendor": "CISCO",
        "region": "IT",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "L2-BNG", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": "Gi0/0/0/23", "sequence": 3, "step": "EVPN", "waitTimeSec": 600},
            {"exclusion": None, "sequence": 4, "step": "L2-BNG", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 5, "step": "CFP2-Port", "waitTimeSec": 0},
        ],
        "trafficOnStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": "Gi0/0/0/23", "sequence": 2, "step": "EVPN", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 3, "step": "CFP2-Port", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 4, "step": "L2-BNG", "waitTimeSec": 600},
        ],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "P&T",
        "deviceVendor": "CISCO",
        "region": "IT",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "BGP", "waitTimeSec": 310},
            {"exclusion": None, "sequence": 3, "step": "EBGP", "waitTimeSec": 0},
        ],
        "trafficOnStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "EBGP", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 3, "step": "BGP", "waitTimeSec": 300},
        ],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "P&T",
        "deviceVendor": "CISCO",
        "region": "UK",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "EBGP", "waitTimeSec": 0},
        ],
        "trafficOnStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "EBGP", "waitTimeSec": 0},
        ],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "SUPER CORE",
        "deviceVendor": "CISCO",
        "region": "IT",
        "status": "SUCCESS",
        "trafficOffStep": [{"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0}],
        "trafficOnStep": [{"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0}],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "SUPER CORE",
        "deviceVendor": "CISCO",
        "region": "UK",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "RSVP", "waitTimeSec": 60},
        ],
        "trafficOnStep": [{"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0}],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "TRANSPORT AGG",
        "deviceVendor": "CISCO",
        "region": "IT",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "L2-BNG", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": "Gi0/0/0/23", "sequence": 3, "step": "EVPN", "waitTimeSec": 600},
            {"exclusion": None, "sequence": 4, "step": "L2-BNG", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 5, "step": "CFP2-Port", "waitTimeSec": 0},
        ],
        "trafficOnStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": "Gi0/0/0/23", "sequence": 2, "step": "EVPN", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 3, "step": "L2-BNG", "waitTimeSec": 600},
            {"exclusion": None, "sequence": 4, "step": "CFP2-Port", "waitTimeSec": 0},
        ],
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "TRANSPORT AGG",
        "deviceVendor": "CISCO",
        "region": "UK",
        "status": "SUCCESS",
        "trafficOffStep": [
            {"exclusion": None, "sequence": 1, "step": "L2-BNG", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 3, "step": "RSVP", "waitTimeSec": 60},
            {"exclusion": None, "sequence": 4, "step": "L2-BNG", "waitTimeSec": 600},
            {"exclusion": None, "sequence": 5, "step": "CDN", "waitTimeSec": 0},
        ],
        "trafficOnStep": [
            {"exclusion": None, "sequence": 1, "step": "ISIS", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 2, "step": "CDN", "waitTimeSec": 0},
            {"exclusion": None, "sequence": 3, "step": "L2-BNG", "waitTimeSec": 600},
        ],
    },
]

final_response7 = [
    {
        "deviceModel": "NCS5K",
        "deviceRole": "super-core",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "UK",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "cdn",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "UK",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "metro-agg",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "UK",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "transport-agg",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": True,
        "region": "UK",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "peer-and-transit",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "UK",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-asbr",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "UK",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-super-core",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "UK",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "comcast-sdc",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "UK",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-xvp",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "UK",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-peer-and-transit",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "UK",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "super-core",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IT",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "cdn",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IT",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "metro-agg",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": True,
        "region": "IT",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "transport-agg",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": True,
        "region": "IT",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "peer-and-transit",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IT",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-asbr",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IT",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-super-core",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IT",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "comcast-sdc",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IT",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-xvp",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IT",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-peer-and-transit",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IT",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "super-core",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "DE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "cdn",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "DE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "metro-agg",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "DE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "transport-agg",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "DE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "peer-and-transit",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "DE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-asbr",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "DE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-super-core",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "DE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "comcast-sdc",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "DE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-xvp",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "DE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-peer-and-transit",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "DE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "super-core",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "cdn",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "metro-agg",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "transport-agg",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "peer-and-transit",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-asbr",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-super-core",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "comcast-sdc",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-xvp",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IE",
    },
    {
        "deviceModel": "NCS5K",
        "deviceRole": "group-peer-and-transit",
        "deviceVendor": "CISCO",
        "isServiceCheckRequired": False,
        "region": "IE",
    },
]

read_cases = [
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": final_response,
        "kwargs": {
            "_include": "brief",
            "limit": 3,
            "offset": 0,
            "region": "UK",
            "deviceVendor": "CISCO",
            "deviceModel": "NCS5K",
            "username": "",
            "token_info": {},
        },
        "count": 4,
    },
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": final_response5,
        "kwargs": {
            "_include": "brief",
            "limit": 1,
            "offset": 0,
            "currentVersion": "7.1.0",
            "currentLabel": "7.1.0-V1",
            "currentState": "Deprecated",
            "targetVersion": "7.5.1",
            "targetLabel": "7.5.1-V1",
            "targetState": "Current",
            "username": "",
            "token_info": {},
        },
        "count": 1,
    },
    {
        "traffic_data": diversion_list,
        "final_response": final_response6,
        "kwargs": {"_include": "trafficDiversion", "username": "", "token_info": {}},
        "count": 1,
    },
    {
        "source_data": source_list,
        "target_data": target_list,
        "custom_config_data": custom_config_list,
        "role": namedtuple("device_role", "role")("transport-agg"),
        "final_response": final_response2,
        "stage": "SUCCESS",
        "kwargs": {"region": "UK", "deviceVendor": "CISCO", "deviceModel": "NCS5K", "username": "", "token_info": {}},
        "count": 4,
    },
    {
        "source_data": [],
        "target_data": [],
        "stage": "FAILURE",
        "kwargs": {
            "region": "UK",
            "_include": "brief",
            "deviceVendor": "NOKIA",
            "offset": 0,
            "username": "",
            "token_info": {},
        },
        "final_response": {
            "status": "FAILURE",
            "errorCategory": "FAILED",
            "errors": [
                {
                    "code": "ERR-000-097-1010",
                    "message": "Validation Failed: For the device vendor: NOKIA, region: UK data " "is not found",
                }
            ],
        },
        "count": 0,
    },
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": {
            "status": "FAILURE",
            "errorCategory": "FAILED",
            "errors": [{"code": "ERR-000-097-1016", "message": "Given offset is exceeding than total response"}],
        },
        "kwargs": {
            "_include": "brief",
            "limit": 1,
            "offset": 9,
            "region": "UK",
            "deviceVendor": "CISCO",
            "deviceModel": "NCS5K",
            "username": "",
            "token_info": {},
        },
        "count": 4,
    },
    {
        "kwargs": {
            "osVersionDeviceRegionId": 1,
            "region": "UK",
            "_include": "brief",
            "deviceVendor": "NOKIA",
            "username": "",
            "token_info": {},
        },
        "source_data": [],
        "target_data": [],
        "stage": "FAILURE",
        "final_response": {
            "status": "FAILURE",
            "errorCategory": "FAILED",
            "errors": [
                {
                    "code": "ERR-000-097-1011",
                    "message": "Validation Failed: Unsupported parameter combination",
                }
            ],
        },
        "count": 0,
    },
    {
        "package_data": package_list,
        "image_data": image_list,
        "kwargs": {"osVersionDeviceRegionId": 9, "username": "", "token_info": {}},
        "final_response": final_response4,
        "count": 1,
    },
    {
        "package_data": package_list,
        "image_data": image_list,
        "kwargs": {"osVersionDeviceRegionId": 15, "username": "", "token_info": {}},
        "final_response": {
            "status": "FAILURE",
            "errorCategory": "FAILED",
            "errors": [
                {
                    "code": "ERR-000-097-1014",
                    "message": "Validation Failed: Invalid osVersionDeviceRegionId ID",
                }
            ],
        },
        "count": 0,
    },
    {
        "source_data": source_list_2,
        "target_data": target_list,
        "kwargs": {"osVersionUpgradeId": 8, "username": "", "token_info": {}},
        "final_response": {
            "status": "FAILURE",
            "errorCategory": "FAILED",
            "errors": [
                {
                    "code": "ERR-000-097-1013",
                    "message": "Validation Failed: osVersionUpgradeId ID is not matching current os id",
                }
            ],
        },
        "count": 2,
    },
    {
        "source_data": source_list_1,
        "target_data": target_list,
        "custom_config_data": custom_config_list,
        "role": namedtuple("device_role", "role")("transport-agg"),
        "kwargs": {"osVersionUpgradeId": 5, "username": "", "token_info": {}},
        "final_response": final_response3,
        "count": 2,
    },
    {
        "source_data": source_list_1,
        "target_data": target_list,
        "kwargs": {"osVersionUpgradeId": 5, "username": "", "token_info": {}},
        "final_response": {
            "status": "FAILURE",
            "errorCategory": "FAILED",
            "errors": [
                {
                    "code": "ERR-000-097-1012",
                    "message": "Validation Failed: Invalid osVersionUpgradeId ID",
                }
            ],
        },
        "count": 0,
    },
]

test_cases_get_custom_config = [
    {
        "kwargs": {"region": "UK", "deviceVendor": "CISCO", "deviceModel": "NCS5K", "username": "", "token_info": {}},
        "custom_config_data": custom_config_list_1,
        "config_id": 3,
        "count": 2,
    },
]

error_params = [
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": final_response,
        "stage": "FAILURE",
        "_include": "brief",
        "exception": Exception("Error occurred"),
        "value": "Exception",
        "limit": 3,
        "offset": 0,
        "region": "UK",
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "message": "Generic Exception occurred while performing read upgrade details from os device region tables",
    },
]

source_error_params = [
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": final_response,
        "stage": "FAILURE",
        "_include": "brief",
        "exception": AttributeError("Error occurred"),
        "value": "AttributeError",
        "limit": 3,
        "offset": 0,
        "region": "UK",
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "message": "Exception occurred while performing source query from sequence and phase tables",
    },
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": final_response,
        "stage": "FAILURE",
        "_include": "brief",
        "exception": Exception("Error occurred"),
        "value": "Exception",
        "limit": 3,
        "offset": 0,
        "region": "UK",
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "message": "Generic Exception occurred while performing source query from sequence and phase tables",
    },
]

target_error_params = [
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": final_response,
        "stage": "FAILURE",
        "_include": "brief",
        "exception": AttributeError("Error occurred"),
        "value": "AttributeError",
        "limit": 3,
        "offset": 0,
        "region": "UK",
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "message": "Exception occurred while performing target query from sequence and phase tables",
    },
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": final_response,
        "stage": "FAILURE",
        "_include": "brief",
        "exception": Exception("Error occurred"),
        "value": "Exception",
        "limit": 3,
        "offset": 0,
        "region": "UK",
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "message": "Generic Exception occurred while performing target query from sequence and phase tables",
    },
]

os_error_params = [
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": final_response,
        "stage": "FAILURE",
        "_include": "brief",
        "exception": AttributeError("Error occurred"),
        "value": "AttributeError",
        "limit": 3,
        "offset": 0,
        "region": "UK",
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "message": "Exception occurred while performing os details query from os device region tables",
    },
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": final_response,
        "stage": "FAILURE",
        "_include": "brief",
        "exception": Exception("Error occurred"),
        "value": "Exception",
        "limit": 3,
        "offset": 0,
        "region": "UK",
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "message": "Generic Exception occurred while performing os details query from os device region tables",
    },
]

traffic_error_params = [
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": final_response,
        "stage": "FAILURE",
        "_include": "brief",
        "exception": AttributeError("Error occurred"),
        "value": "AttributeError",
        "limit": 3,
        "offset": 0,
        "region": "UK",
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "message": "Exception occurred while performing traffic diversion query from traffic and protocol tables",
    },
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": final_response,
        "stage": "FAILURE",
        "_include": "brief",
        "exception": Exception("Error occurred"),
        "value": "Exception",
        "limit": 3,
        "offset": 0,
        "region": "UK",
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "message": "Generic Exception occurred while performing traffic diversion query "
        "from traffic and protocol tables",
    },
]

filter_error_params = [
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": final_response,
        "stage": "FAILURE",
        "_include": "brief",
        "exception": AttributeError("Error occurred"),
        "value": "AttributeError",
        "limit": 3,
        "offset": 0,
        "region": "UK",
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "message": "Exception occurred while performing filter_traffic_diversion_details from traffic protocol table",
    },
    {
        "source_data": source_list,
        "target_data": target_list,
        "final_response": final_response,
        "stage": "FAILURE",
        "_include": "brief",
        "exception": Exception("Error occurred"),
        "value": "Exception",
        "limit": 3,
        "offset": 0,
        "region": "UK",
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "message": "Generic Exception occurred while performing filter_traffic_diversion_details"
        " from traffic protocol table",
    },
]

duplicate_case = {
    "package_data": package_list,
    "image_data": image_list,
    "kwargs": {"osVersionDeviceRegionId": 15, "username": "", "token_info": {}},
    "final_response": {
        "status": "FAILURE",
        "errorCategory": "FAILED",
        "errors": [
            {
                "code": "ERR-000-097-1014",
                "message": "Validation Failed: Invalid osVersionDeviceRegionId ID",
            }
        ],
    },
    "count": 0,
}

service_error_params = [
    {
        "exception": AttributeError("Error occurred"),
        "region": "UK",
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "value": "AttributeError",
        "message": "Exception occurred while performing service check query from service_check table",
    },
    {
        "exception": Exception("Error occurred"),
        "region": "UK",
        "deviceVendor": "CISCO",
        "deviceModel": "NCS5K",
        "value": "Exception",
        "message": "Generic Exception occurred while performing service check query " "from service_check table",
    },
]

service_check_case = {
    "service_data": service_list,
    "kwargs": {"_include": "serviceChecks", "username": "", "token_info": {}},
    "final_response": final_response7,
    "count": 1,
}

final_response8 = {
    "limit": 1,
    "offset": 0,
    "resultSet": [
        {
            "comments": "7.3.0-V1 is in deprecated status",
            "deviceModel": "NCS5K",
            "deviceVendor": "CISCO",
            "osDetails": {
                "imageFiles": [
                    {
                        "fileName": "/bluebird/ios-xr/7.3.0/NCS540/install-image.iso",
                        "imageSize": 2742723234,
                        "imageType": "iso",
                        "md5Value": "ec55d3e698d289f2afd663725127bace",
                    }
                ],
                "packageDetails": (
                    {
                        "packages": [
                            "ncs540-li-1.0.0.0-r732",
                            "ncs540-eigrp-1.0.0.0-r732",
                            "ncs540-isis-1.0.0.0-r732",
                        ],
                        "type": "XR",
                    },
                    {
                        "packages": [
                            "ncs540-sysadmin-shared-7.3.0.1-r732.CSCvx53252",
                            "ncs540-sysadmin-system-7.3.0.2-r732.CSCvy03814",
                            "ncs540-sysadmin-ncs540-7.3.0.5-r732.CSCvz54957",
                        ],
                        "type": "SYSADMIN-FIX",
                    },
                    {
                        "packages": [
                            "ncs540-sysadmin-shared-7.3.0.1-r732.CSCvx53252",
                            "ncs540-sysadmin-system-7.3.0.2-r732.CSCvy03814",
                            "ncs540-sysadmin-ncs540-7.3.0.5-r732.CSCvz54957",
                        ],
                        "type": "SYSADMIN-MOD",
                    },
                ),
            },
            "osLabel": "7.3.0-V1",
            "osStatus": "Deprecated",
            "osVersion": "7.3.0",
            "osVersionDeviceRegionId": 2,
            "region": "DE",
            "status": "SUCCESS",
        }
    ],
    "status": "SUCCESS",
    "total": 1,
}

image_detail_case = {
    "package_data": package_list,
    "image_data": image_list,
    "kwargs": {"_include": "imageDetail", "username": "", "token_info": {}},
    "final_response": final_response8,
    "count": 1,
}
