"""
__author__ = "Sky UK Ltd"
__copyright__ = Copyright © Sky CP Limited 2023.
All rights reserved. No part of this work may be reproduced,
stored in a retrieval system of any nature, or transmitted,
in any form or by any means including photocopying
and recording, without the prior written permission of Sky,
the copyright owner.
__licence__ = "subject to the terms of the licence with Sky UK Ltd'
__version__ = "1.0"
"""
db_errors = {
    "ArgumentError": "Raised due to an invalid or conflicting function argument",
    "CircularDependencyError": "Raised due to a circular dependency is detected by topological sorts",
    "CompileError": "Raised due to an error during SQL compilation",
    "ConcurrentModificationError": "Raised due to rows modified outside of the unit of work",
    "DBAPIError": "Raised when the execution of a database operation fails",
    "DatabaseError": "Raised when executing sql with bad syntax or sql that throws an error",
    "DisconnectionError": "Raised because a disconnect is detected on a raw DB-API connection",
    "FlushError": "Raised when an invalid condition is detected during flush.",
    "IdentifierError": "Raised when a schema name exceeds the maximum character limit.",
    "IntegrityError": "Raised when the relational integrity of the database is affected",
    "InterfaceError": "Raised by drivers in the context of the database connection being dropped"
    " or not being able to connect to the database.",
    "InternalError": "Raised by drivers when SQL Server limits the number of identifiers and constants that "
    "can be contained in a single expression of a query.",
    "InvalidRequestError": "Raised because SQLAlchemy is asked to perform an action that it can't do",
    "NoReferenceError": "Raised by ForeignKey when a reference cannot be resolved.",
    "NoReferencedColumnError": "Raised by ForeignKey when the referred Column cannot be located.",
    "NoReferencedTableError": "Raised by ForeignKey when the referred Table cannot be located.",
    "NotSupportedError": "Raised when connection that does not support transaction or has transactions turned off.",
    "OperationalError": "Raised by drivers in the context of the database connection being dropped"
    " or not being able to connect to the database.",
    "ProgrammingError": "Raised when table not found or already exists, syntax error in the SQL statement.",
    "SADeprecationWarning": "Issued once per usage of a deprecated API.",
    "SAPendingDeprecationWarning": "Issued once per usage of a deprecated API.",
    "SAWarning": "Issued at runtime.",
    "SQLAlchemyError": "Generic error class.",
    "SQLError": "Raised when the execution of a database operation fails.",
    "UnboundExecutionError": "Raised when SQL is attempted without a database connection to execute it on.",
    "UnmappedColumnError": "Raised when a mapping operation is requested on an unknown column.",
    "sqlalchemy.orm.exc.ConcurrentModificationError": "Raised because rows have been modified outside",
    "sqlalchemy.orm.exc.FlushError": "Raised when an invalid condition is detected during flush.",
    "sqlalchemy.orm.exc.MultipleResultsFound": "Raised because a single database result was required, "
    "but more than one were found.",
    "sqlalchemy.orm.exc.NoResultFound": "Raised when a database result was required, but none were found.",
    "sqlalchemy.orm.exc.ObjectDeletedError": "Raised because a refresh operation failed to re-retrieve an object's row",
    "sqlalchemy.orm.exc.UnmappedClassError": "Raised because a mapping operation is requested for an unknown class",
    "sqlalchemy.orm.exc.UnmappedColumnError": "Raised because a mapping operation is requested on an unknown column",
    "sqlalchemy.orm.exc.UnmappedError": "An error related to unmapped entities.",
    "sqlalchemy.orm.exc.UnmappedInstanceError": "Raised when an operation was requested on an unknown instance.",
    "DatabaseConnectionError": "Error occurred while connecting to the database.",
    "QueryExecutionError": "Error occurred while executing the SQL query.",
    "DataAccessError": "Error occurred while accessing data from the database.",
    "IntegrityConstraintError": "Integrity constraint violation occurred.",
    "TransactionError": "Error occurred while managing transactions in the database.",
    "DeadlockError": "Deadlock occurred while executing database operations.",
    "TimeoutError": "Timeout occurred while waiting for a database operation.",
    "PermissionError": "Insufficient permissions to perform the database operation.",
    "ConnectionError": "Error occurred while establishing or maintaining a database connection.",
    "SyntaxError": "Syntax error in the SQL statement.",
    "ForeignKeyError": "Foreign key constraint violation occurred.",
    "NotUniqueError": "Unique constraint violation occurred.",
    "ConstraintViolationError": "Constraint violation occurred.",
    "DataError": "Error in the format or type of the data in the database.",
    "NoSuchTableError": "The requested table does not exist in the database.",
    "NoSuchColumnError": "The requested column does not exist in the database table.",
    "IndexError": "Error related to database indexing.",
    "LockError": "Error occurred while acquiring or releasing database locks.",
    "ConnectionPoolError": "Error occurred while managing the connection pool.",
    "MetadataError": "Error related to database metadata.",
    "StatementError": "Error related to the SQL statement.",
    "ServerUnavailableError": "The database server is currently unavailable.",
    "TransactionRollbackError": "Error occurred while rolling back a transaction.",
    "AuthenticationError": "Error occurred while authenticating with the database server.",
    "DatabaseNotFound": "The specified database does not exist.",
    "DatabaseAccessDenied": "Access to the database is denied.",
    "DataTooLongError": "The data exceeds the maximum allowed length.",
    "ConcurrencyError": "Concurrency-related error occurred.",
    "ConstraintError": "Generic constraint-related error.",
    "InvalidOperationError": "Invalid operation performed on the database.",
}
